apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhil-eta-deploy
  labels:
    app: akhil-eta-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: akhil-eta-app
  template:
    metadata:
      labels:
        app: akhil-eta-app
    spec:
      containers:
      - name: akhil-eta-container
        image: akhilsru3/akhil-kube-image:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: akhil-eta-np-service
  labels:
    app: akhil-eta-app
spec:
  selector:
    app: akhil-eta-app
  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
